# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-11-04 16:25:15
"""
import arcpy


def eez_dissolve(eez_v12_shp, expression, eez_v12_SpatialJoin, if_print=0):  # eez
    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True

    # Process: 按属性选择图层 (按属性选择图层) (management)
    eez_v12_Layer = arcpy.management.SelectLayerByAttribute(in_layer_or_view=eez_v12_shp,
                                                            selection_type="NEW_SELECTION", where_clause=expression,
                                                            invert_where_clause="")

    # Process: 面转线 (面转线) (management)
    eez_v12_Layer_Line = "in_memory/eez_v12_Layer_Line "
    arcpy.management.PolygonToLine(in_features=eez_v12_Layer, out_feature_class=eez_v12_Layer_Line,
                                   neighbor_option="IDENTIFY_NEIGHBORS")

    # Process: 要素转点 (要素转点) (management)
    eez_v12_Layer_Point = "in_memory/eez_v12_Layer_Point"
    arcpy.management.FeatureToPoint(in_features=eez_v12_Layer, out_feature_class=eez_v12_Layer_Point,
                                    point_location="INSIDE")

    # Process: 要素转面 (要素转面) (management)
    eez_v12_Layer_temp = "in_memory/eez_v12_Layer_temp"
    arcpy.management.FeatureToPolygon(in_features=[eez_v12_Layer_Line], out_feature_class=eez_v12_Layer_temp,
                                      cluster_tolerance="", attributes="ATTRIBUTES", label_features=eez_v12_Layer_Point)

    # Process: 融合 (融合) (management)
    eez_v12_Dissolve = "in_memory/eez_v12_Dissolve"
    arcpy.management.Dissolve(in_features=eez_v12_Layer_temp, out_feature_class=eez_v12_Dissolve, dissolve_field=[],
                              statistics_fields=[], multi_part="MULTI_PART", unsplit_lines="DISSOLVE_LINES",
                              concatenation_separator="")

    # Process: 空间连接 (空间连接) (analysis)
    arcpy.analysis.SpatialJoin(target_features=eez_v12_Dissolve, join_features=eez_v12_Layer_Point,
                               out_feature_class=eez_v12_SpatialJoin, join_operation="JOIN_ONE_TO_ONE",
                               join_type="KEEP_ALL", match_option="INTERSECT")
    # 判断是否打印
    if if_print:
        print(fr'{expression} finished.')


if __name__ == '__main__':
    # Global Environment settings
    eez_output_temp = fr'E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\World_EEZ_v12_20231025\eez_v12_dissolve.gdb'
    arcpy.env.workspace = fr"E:\_OrderingProject\F_IslandsBoundaryChange\a_ArcMap\IslandsBoundaryChange"
    for eez_uid in range(159, 286):
        eez_dissolve(
            eez_v12_shp="E:\\_OrderingProject\\F_IslandsBoundaryChange\\b_ArcData\\World_EEZ_v12_20231025\\eez_v12.shp",
            expression=fr"eez_UID = '{eez_uid}'",
            eez_v12_SpatialJoin=fr"{eez_output_temp}\eez_{eez_uid}",
            if_print=1
        )
