# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-11-15 09:03:13
"""
import time
import arcpy
from list_files_with_extension import list_files_with_extension


def consume_time_formatted(start_s, end_s):
    # 初始化时间
    seconds = abs(end_s - start_s)

    # 规范化输出
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    seconds = int(seconds % 60)

    time_print = f"{hours:02}:{minutes:02}:{seconds:02}"
    print(f"Task completed in: {time_print}")

    return end_s

def Model5(input_tif_list, shp_merge):
    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True

    # Process: 合并 (合并) (management)
    # to_polygon = "in_memory\shp_merge_Polygon"
    to_polygon = r'E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\GEE_Landsat_output\_12_merge.shp'
    arcpy.management.Merge(inputs=input_tif_list, output=to_polygon, add_source="NO_SOURCE_INFO")
    print('1')


    # Process: 修复几何 (修复几何) (management)
    to_polygon_temp = arcpy.management.RepairGeometry(in_features=to_polygon, delete_null="DELETE_NULL", validation_method="ESRI")[0]
    print('2')

    # Process: 融合 (融合) (management)
    to_dissolve = "in_memory\shp_dissolve"
    arcpy.management.Dissolve(in_features=to_polygon_temp, out_feature_class=shp_merge, dissolve_field=[],
                              statistics_fields=[], multi_part="MULTI_PART", unsplit_lines="DISSOLVE_LINES",
                              concatenation_separator="")
    print('3')
    #
    # # Process: 面转线 (面转线) (management)
    # to_line = "in_memory\shp_merge_PolygonToLine"
    # arcpy.management.PolygonToLine(in_features=to_dissolve, out_feature_class=to_line,
    #                                neighbor_option="IDENTIFY_NEIGHBORS")
    # print('4')
    #
    # # Process: 要素转面 (要素转面) (management)
    # to_polygon = shp_merge
    # arcpy.management.FeatureToPolygon(in_features=[to_line], out_feature_class=to_polygon, cluster_tolerance="",
    #                                   attributes="ATTRIBUTES", label_features="")



if __name__ == '__main__':
    # 开始时间
    start_time = time.time()

    arcpy.env.workspace = r"E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\GEE_Landsat_output\YY_2015_12"
    # 获取符合条件的文件名列表
    dbndwi_files = list_files_with_extension(
        folder_path=r"E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\GEE_Landsat_output\YY_2015_12",
        extension=r"_extract.shp", if_print=0)

    # Global Environment settings
    Model5(input_tif_list=dbndwi_files,
           shp_merge=r'E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\GEE_Landsat_output\Glo_Div_12_merge.shp')

    # 计算差值即为程序运行时间
    consume_time_formatted(start_s=start_time, end_s=time.time())
