# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-09-18 20:35:14
"""
import arcpy


def extract_by_mask(origin_tif, mask, identifier, output_tif):  # _draft

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True

    # 确认掩膜范围 shp_mask
    # 加载Shapefile/GDB Layer
    shapefile_layer = fr"in_memory\mask_layer"
    feature_path = mask
    arcpy.MakeFeatureLayer_management(feature_path, shapefile_layer)

    # 标记id identifier
    where_clause = f"ALL_Uniq = {identifier}"
    arcpy.SelectLayerByAttribute_management(shapefile_layer, "NEW_SELECTION", where_clause)

    ISID_224209_tif = arcpy.Raster(origin_tif)
    _224209_shp = shapefile_layer

    # Process: 按掩膜提取 (按掩膜提取) (sa)
    ISID_extract_tif = output_tif
    extract_by_mask = ISID_extract_tif
    with arcpy.EnvManager(extent=_224209_shp):
        ISID_extract_tif = arcpy.sa.ExtractByMask(in_raster=ISID_224209_tif, in_mask_data=_224209_shp,
                                                  extraction_area="INSIDE", analysis_extent=ISID_224209_tif)
        ISID_extract_tif.save(extract_by_mask)

    # 清除选择状态
    arcpy.SelectLayerByAttribute_management(shapefile_layer, "CLEAR_SELECTION")

    print(fr"Extracting valid tif: {output_tif}")


if __name__ == '__main__':
    extract_by_mask(origin_tif='E:\\_OrderingProject\\F_IslandsBoundaryChange\\a_ArcData\\GEE_valid\\ISID_224209_zoom_ND.tif',
                    mask="E:\\_OrderingProject\\F_IslandsBoundaryChange\\a_ArcData\\temp\\224209.shp",
                    identifier='',
                    output_tif="E:\\_OrderingProject\\F_IslandsBoundaryChange\\a_ArcData\\GEE_valid\\ISID_224209_zoom_ND_extract.tif")
    pass
# E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\SmallIslands_con_buffer.gdb\Africa_buffer
