# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-09-19 19:56:45
"""
import arcpy

def caculate_area_length(origin_fields_shp):  # field

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True

    # 标记 id 从 shp 名称里取得
    unique_id = origin_fields_shp.split('_')[-2]

    # Process: 计算字段 (计算字段) (management)
    ISID_224209_subpixel_2_ = arcpy.management.CalculateField(in_table=origin_fields_shp, field="UID_ISID", expression=unique_id, expression_type="PYTHON3", code_block="", field_type="TEXT", enforce_domains="NO_ENFORCE_DOMAINS")[0]

    # Process: 计算几何属性 (计算几何属性) (management)
    ISID_224209_subpixel_4_ = arcpy.management.CalculateGeometryAttributes(in_features=ISID_224209_subpixel_2_, geometry_property=[["Geo_Area", "AREA_GEODESIC"], ["Geo_Length", "PERIMETER_LENGTH_GEODESIC"]], length_unit="KILOMETERS", area_unit="SQUARE_KILOMETERS", coordinate_system="", coordinate_format="SAME_AS_INPUT")[0]

    print(fr"Caculate area and length: {origin_fields_shp}")

if __name__ == '__main__':
    shp_path = fr"E:\_OrderingProject\F_IslandsBoundaryChange\a_ArcData\GEE_valid\ISID_224209_subpixel.shp"
    caculate_area_length(origin_fields_shp=shp_path)
