# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-04-19 13:25:47
"""
import os
import arcpy

arcpy.env.overwriteOutput = True

def read_txt_to_list(file_path: str) -> list[str]:
    """
    读取文本文件内容为列表
    :param file_path: 文本文件路径
    :return: 行内容组成的字符串列表
    """
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            return [line.strip() for line in file.readlines()]
    except Exception as e:
        print(f"[ERROR] 读取文件失败 {file_path}: {e}")
        return []

def main():
    list_year = ['2010', '2015', '2020']
    list_sids = read_txt_to_list(file_path=fr"draft.txt")

    # for year in ['2020']:
    for year in list_year:
        for sids in ['SUR']:
        # for sids in list_sids:

            shp_input = fr"E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\temp\h_shp_merge\{sids}\{sids}_{year}.shp"
            shp_line_smooth = fr"E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\temp\i_shp_smooth\{sids}\{sids}_CL_{year}.shp"
            shp_polygon_smooth = fr"E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\temp\i_shp_smooth\{sids}\{sids}_BV_{year}.shp"
            os.makedirs(os.path.dirname(shp_polygon_smooth), exist_ok=True)

            # Process: 合并 (合并) (management)
            temp_merge = fr'in_memory\shp_merge'
            arcpy.management.Merge(
                inputs=[shp_input],
                output=temp_merge)

            # Process: 成对融合 (成对融合) (analysis)
            temp_dissolve = fr'in_memory\shp_dissolve'
            arcpy.analysis.PairwiseDissolve(
                in_features=temp_merge, out_feature_class=temp_dissolve,
                multi_part="MULTI_PART")

            # Process: 平滑要素
            arcpy.cartography.SmoothPolygon(
                in_features=temp_dissolve,
                out_feature_class=shp_polygon_smooth,  # 输出平滑处理后的图层
                algorithm="PAEK",  # 使用 PAEK 算法进行平滑
                tolerance="90 Meters",  # 平滑的容忍度为 50 米
                endpoint_option="FIXED_ENDPOINT",  # 固定端点
                error_option="NO_CHECK"  # 不检查错误
            )

            # Process: 要素转线
            arcpy.management.FeatureToLine(
                in_features=shp_polygon_smooth,
                out_feature_class=shp_line_smooth)

            # Process: 计算几何属性 (计算几何属性) (management)
            arcpy.management.CalculateGeometryAttributes(
                in_features=shp_polygon_smooth,
                geometry_property=[["Leng_Geo", "PERIMETER_LENGTH_GEODESIC"], ["Area_Geo", "AREA_GEODESIC"]],
                length_unit="KILOMETERS", area_unit="SQUARE_KILOMETERS", coordinate_format="SAME_AS_INPUT")

            print(fr'merge_calculate: {shp_polygon_smooth}')


if __name__ == '__main__':
    main()
