# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-06-29 11:20:42
"""
import os

import arcpy
from osgeo import ogr

arcpy.env.overwriteOutput = True

def poi_kml(shp_poi_check, shp_poi, kml_select):  # _draft

    # Process: 按位置选择图层 (按位置选择图层) (management)
    layer_shp_select = arcpy.management.SelectLayerByLocation(
        in_layer=[shp_poi_check], overlap_type="INTERSECT",
        select_features=shp_poi, search_distance="100 Meters",
        selection_type="NEW_SELECTION",
        )
    shp_select = kml_select.replace(".kml", ".shp")
    arcpy.conversion.ExportFeatures(
        in_features=layer_shp_select,
        out_features=shp_select
    )
    arcpy.management.SelectLayerByAttribute(layer_shp_select, "CLEAR_SELECTION")

    # 打开 SHP 文件
    input_datasource = ogr.Open(shp_select, 0)  # 0 表示只读模式
    if input_datasource is None:
        print("无法打开 SHP 文件，请检查文件路径是否正确！")
        return

    # 获取第一个图层（通常 SHP 文件只有一个图层）
    input_layer = input_datasource.GetLayer()

    # 创建 KML 文件
    driver = ogr.GetDriverByName('KML')  # 指定输出格式为 KML
    output_datasource = driver.CreateDataSource(kml_select)
    if output_datasource is None:
        print("无法创建 KML 文件，请检查文件路径是否正确！")
        return

    # 复制图层结构到 KML 文件
    output_layer = output_datasource.CopyLayer(input_layer, input_layer.GetName())

    # 保存并关闭数据源
    input_datasource.Destroy()
    output_datasource.Destroy()

    print(f"转换完成！KML 文件已保存到 {kml_select}")


def read_txt_to_list(file_path: str) -> list[str]:
    """
    读取文本文件内容为列表
    :param file_path: 文本文件路径
    :return: 行内容组成的字符串列表
    """
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            return [line.strip() for line in file.readlines()]
    except Exception as e:
        print(f"[ERROR] 读取文件失败 {file_path}: {e}")
        return []


if __name__ == '__main__':
    list_year = ['2010', '2015', '2020']
    list_sids = read_txt_to_list(file_path=fr"SIDS_37.txt")

    for sid in list_sids:
        for year in list_year:
            shp_stp = fr"E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\_AccuracyEvaluation\{sid}\{year}\StP_{sid}_{year[-2:]}.shp"
            shp_sp = fr"E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\_AccuracyEvaluation\{sid}\{year}\SP_{sid}_{year[-2:]}.shp"
            kml_out = fr"E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\_AccuracyEvaluation\_kml\{sid}\{sid}_match_{year}.kml"
            os.makedirs(os.path.dirname(kml_out), exist_ok=True)
            poi_kml(shp_poi_check=shp_stp, shp_poi=shp_sp, kml_select=kml_out)


