# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-04-19 13:25:47
"""
import os
import arcpy


def merge_calculate(in_data_list, out_data):
    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True

    # Process: 合并 (合并) (management)
    temp_merge = fr'in_memory\shp_merge'
    arcpy.management.Merge(
        inputs=in_data_list,
        output=temp_merge)

    # Process: 成对融合 (成对融合) (analysis)
    arcpy.analysis.PairwiseDissolve(
        in_features=temp_merge, out_feature_class=out_data,
        multi_part="MULTI_PART")

    # Process: 计算几何属性 (计算几何属性) (management)
    output_path = arcpy.management.CalculateGeometryAttributes(
        in_features=out_data,
        geometry_property=[["Leng_Geo", "LENGTH_GEODESIC"]],
        length_unit="KILOMETERS", coordinate_format="SAME_AS_INPUT")[0]

    print(fr'merge_calculate: {out_data}')

def SIDS_CL(boun_list, work_path, year):
    print('SIDS_CL start:')

    for boun in boun_list:
        data_sids_path = os.path.join(work_path, boun)
        input_data_list = [os.path.join(data_sids_path, fr"{boun}_CL_{str(year)[-2:]}.shp")]

        # 输出结果
        print("Selected files:", input_data_list)

        # 合并的数据列表
        output_path = os.path.join(data_sids_path, fr'_{boun}_merge_CL.shp')
        merge_calculate(in_data_list=input_data_list, out_data=output_path)



def main():
    boundary_list = ['BHS']

    # for year in [2000, 2010, 2020]:
    for year in [2015]:
        work_path = fr'E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\_ThirdProductEvaluation\SIDS_CL_{str(year)[-2:]}'
        SIDS_CL(boun_list=boundary_list, work_path=work_path, year=year)


if __name__ == '__main__':
    main()
