# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-01-08 09:04:02
"""
import os
import arcpy
import numpy as np
from dbfread import DBF


def calculate_statistics(dbf_file_path):
    """
    计算DBF文件中 'NEAR_DIST' 列的统计数据：
    - 平均值
    - 值小于30的个数百分比
    - 值小于60的个数百分比
    - 标准差
    - 均方根误差 (RMSE)

    参数:
    dbf_file_path (str): DBF文件路径

    返回:
    dict: 包含上述统计数据的字典
    """

    # 读取DBF文件
    dbf = DBF(dbf_file_path, encoding='utf-8')

    # 提取'NEAR_DIST'列的数据
    # near_dist_values = [record['NEAR_DIST'] for record in dbf if 'NEAR_DIST' in record]
    near_dist_values = []
    for record in dbf:
        if 'NEAR_DIST' in record:
            value = record['NEAR_DIST']
            if value >= 0:
                near_dist_values.append(value)

    # 如果没有数据，返回None
    if not near_dist_values:
        return None

    # 将数据转化为numpy数组
    near_dist_values = np.array(near_dist_values)

    # 计算统计值

    count_30 = np.sum(near_dist_values < 30)
    count_60 = np.sum(near_dist_values < 60)
    count_all = len(near_dist_values)
    percent_30 = count_30 / count_all * 100
    percent_60 = count_60 / count_all * 100
    mean_value = np.mean(near_dist_values)
    std_dev = np.std(near_dist_values)
    rmse = np.sqrt(np.mean(near_dist_values ** 2))

    # 返回结果
    return {
        'count_30': count_30,
        'count_60': count_60,
        'count_all': count_all,
        'percent_30': percent_30,
        'percent_60': percent_60,
        'mean_value': mean_value,
        'std_dev': std_dev,
        'rmse': rmse
    }


if __name__ == '__main__':
    # Global Environment settings
    year_list = [2010, 2020]
    sids_cou_list = [
        "ATG",
        "BHS",
        "BLZ",
        "BRB",
        "COM",
        "CPV",
        "CUB",
        "DMA",
        "DOM",
        "FJI",
        "FSM",
        "GNB",
        "GRD",
        "GUY",
        "HTI",
        "JAM",
        "KIR",
        "KNA",
        "LCA",
        "MDV",
        "MHL",
        "MUS",
        "NRU",
        "PLW",
        "PNG",
        "SGP",
        "SLB",
        "STP",
        "SUR",
        "SYC",
        "TLS",
        "TON",
        "TTO",
        "TUV",
        "VCT",
        "VUT",
        "WSM",

    ]

    # sids_cou_list = ['PLW']
    # year_list = [2020]
    print("year gid percent_30	percent_60	mean_value	std_dev	rmse	count_30	count_60	count_all")
    for year in year_list:
        near_dist_values = []
        for sid in sids_cou_list:

            # 示例使用 sids
            folder_path = fr"E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\_AccuracyEvaluation\{sid}\{year}"
            near_table = os.path.join(folder_path, fr'SP_{sid}_{str(year)[-2:]}.dbf')

            # # 第三方数据集初始化
            # folder_path = fr"E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\_AccuracyEvaluation\{sid}\{year}\ThirdPartyDataSource"
            # OSM
            # near_table = os.path.join(folder_path, fr'OSM_SP_{sid}_{str(year)[-2:]}.dbf')
            # # GCL_FCS30
            # near_table = os.path.join(folder_path, fr'GCL_SP_{sid}_{str(year)[-2:]}.dbf')
            # # GSV
            # near_table = os.path.join(folder_path, fr'GSV_SP_{sid}_{str(year)[-2:]}.dbf')

            # 计算DBF文件中 'NEAR_DIST' 列的统计数据
            # statistics = calculate_statistics(near_table)

            # 读取DBF文件------------------------------------------------------------------------------
            dbf = DBF(near_table, encoding='utf-8')

            # 提取'NEAR_DIST'列的数据
            # near_dist_values = [record['NEAR_DIST'] for record in dbf if 'NEAR_DIST' in record]
            for record in dbf:
                if 'NEAR_DIST' in record:
                    value = record['NEAR_DIST']
                    if value >= 0:
                        near_dist_values.append(value)

        # 将数据转化为numpy数组
        near_dist_values = np.array(near_dist_values)

        # 计算统计值
        count_30 = np.sum(near_dist_values < 30)
        count_60 = np.sum(near_dist_values < 60)
        count_all = len(near_dist_values)
        percent_30 = count_30 / count_all * 100
        percent_60 = count_60 / count_all * 100
        mean_value = np.mean(near_dist_values)
        std_dev = np.std(near_dist_values)
        rmse = np.sqrt(np.mean(near_dist_values ** 2))

        print(year, percent_30, percent_60, mean_value, std_dev, rmse, count_30, count_60, count_all)
