# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-11-27 16:11:47
"""
import sys

sys.path.append(r"E:\_OrderingProject\F_IslandsBoundaryChange\f_Python")
from GEE_SIDs import _tools

import arcpy
import os


def Model6(_glo_sids_grids_shp, ABW, ABW_2_):  # 模型6

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True

    # Process: 按位置选择图层 (按位置选择图层) (management)
    select_layer = arcpy.management.SelectLayerByLocation(in_layer=[_glo_sids_grids_shp], overlap_type="INTERSECT",
                                                          select_features=ABW, search_distance="",
                                                          selection_type="NEW_SELECTION",
                                                          invert_spatial_relationship="NOT_INVERT")

    # Process: 导出表 (导出表) (conversion)
    arcpy.conversion.ExportTable(in_table=select_layer, out_table=ABW_2_, where_clause="",
                                 use_field_alias_as_name="NOT_USE_ALIAS", sort_field=[])


if __name__ == '__main__':
    # Global Environment settings
    grid_path = r'E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\d_SIDS_Boundary\SIDS_Grids\_glo_sids_grids.shp'
    sids_folder_path = r'E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\d_SIDS_Boundary\SIDS\AdminDivision'
    sids_output_path = r'E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\d_SIDS_Boundary\SIDS_Grids\SIDS_grid_link'
    sids_names = _tools.list_files_with_extension(
        folder_path=sids_folder_path,
        extension='.shp',
        if_print=1)
    for sids_name in sids_names:
        # name
        sids = sids_name.split('.')[0]
        # path
        sids_path = os.path.join(sids_folder_path, sids_name)

        Model6(_glo_sids_grids_shp=grid_path,
               ABW=sids_path,
               ABW_2_=os.path.join(sids_output_path, f'{sids}_grid.dbf')
               )
