# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-12-02 12:39:06
"""
import os.path

import arcpy
from _tools import list_files_with_extension
from sys import argv


def main(GID_shp_list, merge_output):  # 模型6
    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True

    # Process: 合并 (合并) (management)
    merge_layer = fr"in_memory\_Merge"
    arcpy.management.Merge(inputs=GID_shp_list, output=merge_layer, add_source="NO_SOURCE_INFO")

    # Process: 成对融合 (成对融合) (analysis)
    temp_merge_output = fr"in_memory\temp_merge_output"
    arcpy.analysis.PairwiseDissolve(in_features=merge_layer, out_feature_class=temp_merge_output, multi_part="MULTI_PART")

    # Process: 平滑面 (平滑面) (cartography)
    arcpy.cartography.SmoothPolygon(in_features=temp_merge_output, out_feature_class=merge_output, algorithm="PAEK", tolerance="50 Meters",
                                    endpoint_option="FIXED_ENDPOINT", error_option="NO_CHECK")




if __name__ == '__main__':
    # Global Environment settings

    # 图幅年份
    year = 2000
    # 确定国家 GID
    sids_cou = 'ABW'
    # 有效图幅列表
    sids_path = fr"E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\e_SIDS_Shp\{year}\{sids_cou}"
    # 国家图幅列表
    map_names = list_files_with_extension(folder_path=sids_path, extension='.shp', if_print=1)
    list_map_sids = [os.path.join(sids_path, var) for var in map_names]

    # 国家有效图幅合并
    sids_cou_output = fr"E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\e_SIDS_Shp\{year}\{sids_cou}_{(year%100):02}.shp"

    main(GID_shp_list=list_map_sids, merge_output=sids_cou_output)
