# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-04-19 13:25:47
"""
import os
import arcpy


def merge_calculate(in_data_list, out_data):
    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True

    # Process: 合并 (合并) (management)
    temp_merge = fr'in_memory\shp_merge'
    arcpy.management.Merge(
        inputs=in_data_list,
        output=temp_merge)

    # Process: 成对融合 (成对融合) (analysis)
    arcpy.analysis.PairwiseDissolve(
        in_features=temp_merge, out_feature_class=out_data,
        multi_part="MULTI_PART")

    # Process: 计算几何属性 (计算几何属性) (management)
    output_path = arcpy.management.CalculateGeometryAttributes(
        in_features=out_data,
        geometry_property=[["Leng_Geo", "LENGTH_GEODESIC"]],
        length_unit="KILOMETERS", coordinate_format="SAME_AS_INPUT")[0]

    print(fr'merge_calculate: {out_data}')


def GSV(boun_list, work_path):
    print('GSV start:')

    for boun in boun_list:
        data_sids_path = os.path.join(work_path, boun)
        data_files = os.listdir(data_sids_path)
        input_data_list = [os.path.join(data_sids_path, data) for data in data_files if data.endswith('.shp')]

        # 输出结果
        print("Selected files:", input_data_list)

        # 合并的数据列表
        output_path = os.path.join(data_sids_path, fr'_{boun}_merge.shp')
        merge_calculate(in_data_list=input_data_list, out_data=output_path)

def GMSSD_2015(boun_list, work_path):
    print('GMSSD_2015 start:')

    for boun in boun_list:
        data_sids_path = os.path.join(work_path, boun)
        data_files = os.listdir(data_sids_path)
        input_data_list = [os.path.join(data_sids_path, data) for data in data_files if data.endswith('.shp')]

        # 输出结果
        print("Selected files:", input_data_list)

        # 合并的数据列表
        output_path = os.path.join(data_sids_path, fr'_{boun}_merge.shp')
        merge_calculate(in_data_list=input_data_list, out_data=output_path)

def GCL_FCS30(boun_list, extend_year, work_path):
    print('GCL_FCS30 start:')

    for boun in boun_list:
        data_sids_path = os.path.join(work_path, boun)
        data_files = os.listdir(data_sids_path)
        input_data_list = [os.path.join(data_sids_path, data) for data in data_files if data.endswith('.shp')]

        # 输出结果
        print("Selected files:", input_data_list)

        # 合并的数据列表
        output_path = os.path.join(data_sids_path, fr'_{boun}_merge.shp')
        merge_calculate(in_data_list=input_data_list, out_data=output_path)

def OSM(boun_list, work_path):
    print('OSM start:')

    for boun in boun_list:
        data_sids_path = os.path.join(work_path, boun)
        data_files = os.listdir(data_sids_path)
        input_data_list = [os.path.join(data_sids_path, data) for data in data_files if data.endswith('.shp')]

        # 输出结果
        print("Selected files:", input_data_list)

        # 合并的数据列表
        output_path = os.path.join(data_sids_path, fr'_{boun}_merge.shp')
        merge_calculate(in_data_list=input_data_list, out_data=output_path)

def SIDS_CL(boun_list, work_path, year):
    print('SIDS_CL start:')

    for boun in boun_list:
        data_sids_path = os.path.join(work_path, boun)
        input_data_list = [os.path.join(data_sids_path, fr"{boun}_CL_{str(year)[-2:]}.shp")]

        # 输出结果
        print("Selected files:", input_data_list)

        # 合并的数据列表
        output_path = os.path.join(data_sids_path, fr'_{boun}_merge_CL.shp')
        merge_calculate(in_data_list=input_data_list, out_data=output_path)



def main():
    # 全 57 国家
    boundary_list = [
        "BMU",
        "KNA",
        "MSR",
        "NRU",
        "BRB",
        "DMA",
        "GUM",
        "NIU",
        "SGP",
        "VCT",
        "AIA",
        "CYM",
        "VGB",
        "VIR",
        "ABW",
        "ASM",
        "CUW",
        "GRD",
        "LCA",
        "MTQ",
        "SXM",
        "ATG",
        "GLP",
        "STP",
        "TCA",
        "COM",
        "WSM",
        "TTO",
        "MUS",
        "TUV",
        "PLW",
        "MNP",
        "JAM",
        "PRI",
        "CPV",
        "TLS",
        "TON",
        "COK",
        "BLZ",
        "GNB",
        "SYC",
        "HTI",
        "DOM",
        "VUT",
        "MDV",
        "NCL",
        "KIR",
        "MHL",
        "FSM",
        "FJI",
        "SUR",
        "SLB",
        "BHS",
        "CUB",
        "GUY",
        "PYF",
        "PNG",
    ]
    # 全 37 国家
    boundary_list = ["ATG",
"BHS",
"BLZ",
"BRB",
"COM",
"CPV",
"CUB",
"DMA",
"DOM",
"FJI",
"FSM",
"GNB",
"GRD",
"GUY",
"HTI",
"JAM",
"KIR",
"KNA",
"LCA",
"MDV",
"MHL",
"MUS",
"NRU",
"PLW",
"PNG",
"SGP",
"SLB",
"STP",
"SUR",
"SYC",
"TLS",
"TON",
"TTO",
"TUV",
"VCT",
"VUT",
"WSM",
]

    # GSV -------------------------------------------------------------------------------------------
    # work_path = fr'E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\_ThirdProductEvaluation\GSV'
    # GSV(boun_list=boundary_list, work_path=work_path)
    # -----------------------------------------------------------------------------------------------------------------
    # work_path = fr'E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\_ThirdProductEvaluation\GMSSD_2015'
    # GMSSD_2015(boun_list=boundary_list, work_path=work_path)
    # -----------------------------------------------------------------------------------------------------------------
    # for year in [2010, 2015, 2020]:
    #     work_path = fr'E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\_ThirdProductEvaluation\GCL_FCS30_{str(year)[-2:]}'
    #     GCL_FCS30(boun_list=boundary_list, extend_year=year, work_path=work_path)
    # -----------------------------------------------------------------------------------------------------------------
    # work_path = fr'E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\_ThirdProductEvaluation\OSM'
    # OSM(boun_list=boundary_list, work_path=work_path)
    # -----------------------------------------------------------------------------------------------------------------
    # for year in [2000, 2010, 2020]:
    for year in [2015]:
        work_path = fr'E:\_OrderingProject\F_IslandsBoundaryChange\b_ArcData\_ThirdProductEvaluation\SIDS_CL_{str(year)[-2:]}'
        SIDS_CL(boun_list=boundary_list, work_path=work_path, year=year)


if __name__ == '__main__':
    main()
